version: "3.8"

services:
  server:
    container_name: server
    build: .

  proxy:
    container_name: proxy
    image: "nginx"
    ports:
      - "80:8080"
    volumes:
      - ./proxy_nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
